#### What does Pandas stand for?
- Pandas is a play on the phase "Pandas Data Analysis"
#### What are the 2 collections used in Pandas?
- The two series that are used in Pandas are *Series* and *DataFrames*
#### Name 4 things Pandas can do for us.
1. Pandas allows a user to import data from a .CSV, Excel, and other sources
2. Pandas allows a user to transform datas
3. Pandas allows a user to cleanse data
4. Pandas allows a user to build data visualizations
#### To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- To permanently sort a Dataframe with df.sort() you must use _"inplace=True"_
#### What is a CSV?
- A CSV is shorthand for Comma Seperated Value, it may also refer to other type of seperators
#### When cleaning data what values do we not like in our data?
- When cleaning data it is important to address _Null_ values

In [ ]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np # import numpy 
import random # import random

random_array = np.random.randint(0, 10, (2, 3, 2)) # use the random module to create a random array of (2,3,3) using intergers from 0 - 10

print(random_array) # print it



In [49]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np # import numpy

linearly_spaced_values = np.linspace(0, 20, 6) # use the .linspace function to create 6 values spaced from 0 from 20 

print(linearly_spaced_values) # print it 


[ 0.  4.  8. 12. 16. 20.]


<!-- What does Pandas stand for?
What are the 2 collections used in Pandas?
Name 4 things Pandas can do for us.
To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
What is a CSV?
When cleaning data what values do we not like in our data? -->

In [50]:
# Make a Deep Copy of the above array

copied_array = np.copy(linearly_spaced_values) # call copy to create new variable using the preivious array

copied_array

array([ 0.,  4.,  8., 12., 16., 20.])

In [51]:
import numpy as np # imported numpy again

x = np.array([[25, 16]]) # made them an array
y = np.array([[11, 2], [13, 4]])
z = np.array([[7, 81], [5, 6], [11, 12]])

# Concatenate along the axis
newArrays = np.concatenate((x, y, z), axis=0) # concat the above arrays

print(newArrays)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [52]:
# Sort newArray into sortedArray

sortedArray = newArrays.sort()  # I uesed .sort() to sort the newArray

print(newArrays) # Then I printed it 

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [53]:
# Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

reshapedArray = np.array([[1,2,3],  # I didn't have a reshapedarray variable created
                 [4,5,6],           # I checked and couldn't find where it was supposed to be created
                 [7,8,9],           # I created an array that would allow me to answer the question
                 [10,11,12]])

first, second, third, fourth = reshapedArray # I assigned variables to each list

print(first)  # then I printed it
print(second)
print(third)
print(fourth)



[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [54]:
# Combined and sort the following arrays into one called 'comboArray' 

one = np.array([10, 11, 12, 13, 14, 15, 16, 17]) # create arrays out of the lists
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one,two,three), axis=0) # combine the above arrays on the correct axis
comboArray = np.sort(comboArray)


print(comboArray) # sort it and then print the combined array

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [55]:
# Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element
# print sec2 - all elements from the 3rd element to the last
# print sec3 - all elements from the 4th to the 14th elements
# print sec4 - the last 6 elements
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
# print sec6 - from #20 every even element to the end
# print sec7 - from the last element moving forward, every 5th element.

print(comboArray)
print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:14])
print(comboArray[-24:-10])
print(comboArray[-8:]) 
print(comboArray[27::5]) # last element??

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 21 22 23 24 25 26 27]
[]


In [56]:
import numpy as np
import pandas as pd

# Using Series, create a DataFrame that looks like this:

# Ingredients	Quantity	Unit
# Flour	4	cups
# Milk	1	cup
# Eggs	2	large
# Spam	1	can
# Name: Dinner, dtype: object


ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients") # create indivual series using a list 
quantity = pd.Series([4, 1, 2, 1], name="Quantity")
unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

df = pd.concat([ingredients, quantity, unit], axis=1) # concat the series together

df # show the dataframe


Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [57]:
studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}) # create a dataframes using a dictionary for the provided information

studentData # show that data

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [58]:
# Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]


deserts = pd.Series(["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], name = "deserts") # create a series for the information to be added

studentData['deserts'] = deserts # append the series to the previous data frame

studentData # display the dataframe

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

In [59]:
# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

sortedStudentData = studentData.sort_values(by=['Name', 'address']) # sort the previous dataframe by first name, then address using the sort function

sortedStudentData # display the dataframe


Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

In [61]:
# Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2']) #info from the question

df.to_csv('cows_and_goats.csv') # write to the .csv

In [62]:
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.


vegetables = pd.DataFrame({'green': ['broccoli', 'arugula', 'green beans'],
            'red': ['bell peppers', 'chili pepper', 'tomatoes'],
            'yellow': ['corn', 'squash', 'pumpkin']})  # Create a dataframe of vegetables


vegetables.to_csv('vegetablesByColor.csv') # write the information to a csv

update_vegetables = pd.read_csv('vegetablesByColor.csv') # read the .csv back in

newVeggies = pd.DataFrame({'green': ['cabbage'],
                          'red': ['beets'],
                           'yellow': ['pumpkin']}) # create a new dataframe with an extra veggie

updatedVeggies = pd.concat([vegetables, newVeggies]) # concat the two dataframes 

updatedVeggies.to_csv('vegetables_updated.csv')



